create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password_hash text not null,
  created_at timestamptz default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  title text not null,
  destination text not null,
  start_date date,
  end_date date,
  created_by bigint not null references public.users(id),
  visibility text not null default 'private' check (visibility in ('public','private')),
  created_at timestamptz default now()
);

create table if not exists public.trip_members (
  trip_id bigint not null references public.trips(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text default 'member' check (role in ('owner','member','observer')),
  added_at timestamptz default now(),
  primary key (trip_id, user_id)
);

create table if not exists public.pending_invites (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  email text not null,
  invited_by bigint not null references public.users(id),
  status text not null default 'pending',
  invite_role text not null default 'member' check (invite_role in ('member','observer')),
  email_sent_at timestamptz,
  created_at timestamptz default now(),
  unique (trip_id, email)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  trip_id bigint references public.trips(id) on delete cascade,
  type text not null,
  message text not null,
  status text not null default 'pending',
  invite_role text not null default 'member' check (invite_role in ('member','observer')),
  friend_request_id bigint references public.friend_requests(id) on delete cascade,
  join_request_id bigint references public.join_requests(id) on delete cascade,
  responded_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  sector text not null,
  title text not null,
  provider text,
  confirmation_code text,
  start_date date not null,
  end_date date,
  notes text,
  custom_fields jsonb not null default '{}'::jsonb,
  created_by bigint not null references public.users(id),
  visibility text not null default 'private' check (visibility in ('public','private')),
  created_at timestamptz default now()
);


create table if not exists public.profiles (
  user_id bigint primary key references public.users(id) on delete cascade,
  bio text,
  name_visibility text not null default 'friends' check (name_visibility in ('private','friends','public')),
  email_visibility text not null default 'private' check (email_visibility in ('private','friends','public')),
  bio_visibility text not null default 'friends' check (bio_visibility in ('private','friends','public')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  requester_id bigint not null references public.users(id) on delete cascade,
  addressee_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz default now(),
  responded_at timestamptz,
  unique (requester_id, addressee_id)
);

create table if not exists public.friendships (
  user_id bigint not null references public.users(id) on delete cascade,
  friend_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (user_id, friend_id),
  check (user_id <> friend_id)
);

create table if not exists public.join_requests (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  requester_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz default now(),
  responded_at timestamptz,
  unique (trip_id, requester_id)
);
