create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password_hash text not null,
  created_at timestamptz default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  title text not null,
  destination text not null,
  start_date date,
  end_date date,
  created_by bigint not null references public.users(id),
  created_at timestamptz default now()
);

create table if not exists public.trip_members (
  trip_id bigint not null references public.trips(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text default 'member',
  added_at timestamptz default now(),
  primary key (trip_id, user_id)
);

create table if not exists public.pending_invites (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  email text not null,
  invited_by bigint not null references public.users(id),
  status text not null default 'pending',
  created_at timestamptz default now(),
  unique (trip_id, email)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  trip_id bigint references public.trips(id) on delete cascade,
  type text not null,
  message text not null,
  status text not null default 'pending',
  responded_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  sector text not null,
  title text not null,
  provider text,
  confirmation_code text,
  start_date date not null,
  end_date date,
  notes text,
  custom_fields jsonb not null default '{}'::jsonb,
  created_by bigint not null references public.users(id),
  created_at timestamptz default now()
);
