-- Migration for EXISTING databases (ALTERs only, no table recreation).
-- Safe to run multiple times.

begin;

-- 1) pending_invites table + email_sent_at
create table if not exists public.pending_invites (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  email text not null,
  invited_by bigint not null references public.users(id),
  status text not null default 'pending',
  created_at timestamptz default now(),
  unique (trip_id, email)
);

alter table public.pending_invites
  add column if not exists email_sent_at timestamptz;

-- 2) notifications table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  trip_id bigint references public.trips(id) on delete cascade,
  type text not null,
  message text not null,
  status text not null default 'pending',
  responded_at timestamptz,
  created_at timestamptz default now()
);

-- 3) bookings table upgrades from legacy schema
alter table public.bookings
  add column if not exists start_date date,
  add column if not exists end_date date,
  add column if not exists custom_fields jsonb;

-- Backfill start_date from legacy booking_date when needed.
update public.bookings
set start_date = booking_date
where start_date is null
  and exists (
    select 1
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = 'bookings'
      and c.column_name = 'booking_date'
  );

-- Backfill custom_fields default where null.
update public.bookings
set custom_fields = '{}'::jsonb
where custom_fields is null;

alter table public.bookings
  alter column custom_fields set default '{}'::jsonb;

-- Enforce not-null start_date only after backfill.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'bookings'
      and column_name = 'start_date'
      and is_nullable = 'YES'
  ) then
    alter table public.bookings
      alter column start_date set not null;
  end if;
exception when others then
  -- keep migration idempotent and non-fatal if data is still invalid
  null;
end $$;

-- Optional cleanup: drop legacy booking_date if present.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'bookings'
      and column_name = 'booking_date'
  ) then
    alter table public.bookings drop column booking_date;
  end if;
end $$;

commit;
