-- Social feed + friendships + trip visibility (ALTER-based)
begin;

alter table public.trips
  add column if not exists visibility text not null default 'private';

alter table public.trips
  drop constraint if exists trips_visibility_check;

alter table public.trips
  add constraint trips_visibility_check check (visibility in ('public','private'));

create table if not exists public.profiles (
  user_id bigint primary key references public.users(id) on delete cascade,
  bio text,
  name_visibility text not null default 'friends',
  email_visibility text not null default 'private',
  bio_visibility text not null default 'friends',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  check (name_visibility in ('private','friends','public')),
  check (email_visibility in ('private','friends','public')),
  check (bio_visibility in ('private','friends','public'))
);

create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  requester_id bigint not null references public.users(id) on delete cascade,
  addressee_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz default now(),
  responded_at timestamptz,
  check (status in ('pending','accepted','rejected')),
  unique (requester_id, addressee_id)
);

create table if not exists public.friendships (
  user_id bigint not null references public.users(id) on delete cascade,
  friend_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (user_id, friend_id),
  check (user_id <> friend_id)
);

create table if not exists public.join_requests (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  requester_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz default now(),
  responded_at timestamptz,
  unique (trip_id, requester_id),
  check (status in ('pending','approved','rejected'))
);

alter table public.notifications
  add column if not exists friend_request_id bigint references public.friend_requests(id) on delete cascade,
  add column if not exists join_request_id bigint references public.join_requests(id) on delete cascade;

commit;
